### ISSUE TITLE
Xcode 9 asset catalog color set

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-xcode#2]
> Relocated from arcticicestudio/nord#45
Requested by @ornithocoder

Xcode 9 added color sets to [asset catalogs](https://devstreaming-cdn.apple.com/videos/wwdc/2017/201fz90p4yq582o/201/201_whats_new_in_cocoa_touch.pdf). It can be used in the [Interface Builder](https://developer.apple.com/xcode/interface-builder) and programmatically via `UIColor(named:)`.

It should be added as official Nord asset catalog that can be dragged and dropped into projects. 

![](https://user-images.githubusercontent.com/19753339/27510545-485b7596-5913-11e7-8914-dcb8dc7c724f.png)

Blog Entries:

* [Asset Catalog Changes in Xcode 9](http://martiancraft.com/blog/2017/06/xcode9-assets)
* [Asset catalog colors on Xcode 9](https://blog.zeplin.io/asset-catalog-colors-on-xcode-9-c4fdccc0381a)

**Comment by ornithocoder** [comment]
Thanks! 🎉
